package com.cheatdatabase.helpers

enum class ResponseCode {

    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    PARAMETERS_TOO_SHORT,
    OTHER_ERROR,
    REGISTER_OK,
    LOGIN_OK,
    WRONG_PASSWORD,
    MEMBER_NOT_FOUND,
    MEMBER_BANNED,
    EMAIL_NOT_FOUND,
    RECOVERY_CODE_WRONG,
    RECOVER_ACCOUNT_SUCCESS

}